<?php

/**
 * @file
 * Module file for block_welcome.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * @defgroup block_welcome Welcome Block
 * @ingroup ffw
 * @{
 * Demonstrates code creation of blocks.
 *
 * This module defines blocks that can be
 * displayed on various pages of a site
 */

function block_welcome_theme($existing, $type, $theme, $path) {
  return array(
   'welcome_template' => array(
      'variables' => array('username' => null, 'text' => null, 'image' => null),
      'template' => 'block--welcome-template',
    ),
  );
}

/**
 * @} End of "defgroup block_welcome".
 */
